exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("tires")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("tires").insert([
        {
          id: 1,
          tiretype: "135/80R12",
          size: "12",
          grade: "B",
          stock: "12",
          price: "180",
        },
        {
          id: 2,
          tiretype: "145/65R12",
          size: "12",
          grade: "C",
          stock: "20",
          price: "145",
        },
        {
          id: 3,
          tiretype: "145/80R12",
          size: "12",
          grade: "C",
          stock: "45",
          price: "150",
        },
        {
          id: 4,
          tiretype: "155/80R12",
          size: "12",
          grade: "A",
          stock: "26",
          price: "220",
        },
        {
          id: 5,
          tiretype: "165/80R12",
          size: "12",
          grade: "B",
          stock: "50",
          price: "180",
        },

        {
          id: 6,
          tiretype: "145/70R13",
          size: "13",
          grade: "A",
          stock: "10",
          price: "240",
        },
        {
          id: 7,
          tiretype: "155/65R13",
          size: "13",
          grade: "C",
          stock: "53",
          price: "180",
        },
        {
          id: 8,
          tiretype: "165/60R13",
          size: "13",
          grade: "B",
          stock: "41",
          price: "190",
        },
        {
          id: 9,
          tiretype: "165/70R13",
          size: "13",
          grade: "A",
          stock: "0",
          price: "265",
        },
        {
          id: 10,
          tiretype: "175/80R13",
          size: "13",
          grade: "C",
          stock: "37",
          price: "185",
        },
        {
          id: 11,
          tiretype: "185/80R13",
          size: "13",
          grade: "C",
          stock: "0",
          price: "185",
        },

        {
          id: 12,
          tiretype: "155/55R14",
          size: "14",
          grade: "C",
          stock: "17",
          price: "200",
        },
        {
          id: 13,
          tiretype: "155/70R14",
          size: "14",
          grade: "B",
          stock: "43",
          price: "220",
        },
        {
          id: 14,
          tiretype: "165/60R14",
          size: "14",
          grade: "B",
          stock: "0",
          price: "220",
        },
        {
          id: 15,
          tiretype: "165/70R14",
          size: "14",
          grade: "A",
          stock: "20",
          price: "280",
        },
        {
          id: 16,
          tiretype: "175/65R14",
          size: "14",
          grade: "C",
          stock: "18",
          price: "200",
        },
        {
          id: 17,
          tiretype: "185/70R14",
          size: "14",
          grade: "C",
          stock: "0",
          price: "205",
        },
        {
          id: 18,
          tiretype: "195/65R14",
          size: "14",
          grade: "B",
          stock: "30",
          price: "230",
        },
        {
          id: 19,
          tiretype: "205/55R14",
          size: "14",
          grade: "A",
          stock: "22",
          price: "290",
        },

        {
          id: 20,
          tiretype: "145/65R15",
          size: "15",
          grade: "B",
          stock: "5",
          price: "240",
        },
        {
          id: 21,
          tiretype: "165/50R15",
          size: "15",
          grade: "B",
          stock: "0",
          price: "240",
        },
        {
          id: 22,
          tiretype: "160/60R15",
          size: "15",
          grade: "C",
          stock: "14",
          price: "230",
        },
        {
          id: 23,
          tiretype: "175/65R15",
          size: "15",
          grade: "B",
          stock: "32",
          price: "250",
        },
        {
          id: 24,
          tiretype: "185/60R15",
          size: "15",
          grade: "A",
          stock: "12",
          price: "300",
        },
        {
          id: 25,
          tiretype: "195/50R15",
          size: "15",
          grade: "B",
          stock: "36",
          price: "250",
        },
        {
          id: 26,
          tiretype: "205/55R15",
          size: "15",
          grade: "C",
          stock: "30",
          price: "235",
        },
        {
          id: 27,
          tiretype: "215/60R15",
          size: "15",
          grade: "C",
          stock: "27",
          price: "235",
        },
        {
          id: 28,
          tiretype: "225/65R15",
          size: "15",
          grade: "C",
          stock: "45",
          price: "240",
        },
      ]);
    });
};
